=== finley243/adventure-editor/schemas/enums.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="enumType" type="EnumTypeType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="EnumTypeType">
        <xs:sequence>
            <xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== finley243/adventure-editor/templates/enums.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/enums.xsd">
    <enumType id="interfaceType">
        <value>graphicalChoice</value>
        <value>consoleChoice</value>
        <value>consoleParser</value>
    </enumType>
    <enumType id="weekday">
        <value>monday</value>
        <value>tuesday</value>
        <value>wednesday</value>
        <value>thursday</value>
        <value>friday</value>
        <value>saturday</value>
        <value>sunday</value>
    </enumType>
    <enumType id="pronoun">
        <value>THEY</value>
        <value>HE</value>
        <value>SHE</value>
        <value>IT</value>
        <value>YOU</value>
        <value>I</value>
        <value>WE</value>
        <value>YOUALL</value>
    </enumType>
    <enumType id="areaNameType">
        <value>in</value>
        <value>on</value>
        <value>near</value>
        <value>front</value>
        <value>side</value>
        <value>behind</value>
    </enumType>
    <enumType id="factionRelation">
        <value>NEUTRAL</value>
        <value>HOSTILE</value>
        <value>ALLY</value>
    </enumType>
    <enumType id="sceneFlowType">
        <value>all</value>
        <value>select</value>
        <value>random</value>
    </enumType>
    <enumType id="distance">
        <value>NEAR</value>
        <value>CLOSE</value>
        <value>FAR</value>
        <value>DISTANT</value>
    </enumType>
    <enumType id="direction">
        <value>N</value>
        <value>NE</value>
        <value>E</value>
        <value>SE</value>
        <value>S</value>
        <value>SW</value>
        <value>W</value>
        <value>NW</value>
    </enumType>
    <enumType id="attackTypeCategory">
        <value>single</value>
        <value>targeted</value>
        <value>spread</value>
    </enumType>
    <enumType id="attackTypeWeaponConsumeType">
        <value>none</value>
        <value>destroy</value>
        <value>place</value>
    </enumType>
    <enumType id="objectComponentTypes">
        <value>inventory</value>
        <value>network</value>
        <value>link</value>
        <value>usable</value>
        <value>vehicle</value>
    </enumType>
    <enumType id="itemComponentTypes">
        <value>ammo</value>
        <value>armor</value>
        <value>consumable</value>
        <value>effectable</value>
        <value>equippable</value>
        <value>magazine</value>
        <value>mod</value>
        <value>moddable</value>
        <value>weapon</value>
    </enumType>
    <enumType id="areaRestrictionType">
        <value>PUBLIC</value>
        <value>PRIVATE</value>
        <value>HOSTILE</value>
    </enumType>
    <enumType id="scriptTriggersRoom">
        <value>on_player_enter</value>
        <value>on_player_round</value>
        <value>on_inspect</value>
    </enumType>
    <enumType id="scriptTriggersArea">
        <value>on_player_enter</value>
        <value>on_player_round</value>
        <value>on_inspect</value>
    </enumType>
    <enumType id="scriptTriggersItem">
        <value>on_inspect</value>
    </enumType>
    <enumType id="scriptTriggersObject">
        <value>on_damaged</value>
        <value>on_broken</value>
        <value>on_inspect</value>
    </enumType>
    <enumType id="scriptTriggersActor">
        <value>on_level_up</value>
        <value>on_player_visible_round</value>
        <value>on_reload</value>
        <value>on_take_cover</value>
        <value>on_leave_cover</value>
        <value>on_attack</value>
        <value>on_attack_success</value>
        <value>on_attack_failure</value>
        <value>on_damaged</value>
        <value>on_death</value>
        <value>on_combat_start</value>
        <value>on_combat_end</value>
        <value>on_target_trespassing_start</value>
        <value>on_target_trespassing_end</value>
        <value>on_detect_dead</value>
        <value>on_detect_target_trespassing</value>
        <value>on_detect_target_hostile_area</value>
        <value>on_detect_target_hostile_faction</value>
        <value>on_detect_target_passive</value>
        <value>on_trespassing_become_hostile</value>
    </enumType>
</data>
