=== finley243/adventure-editor/schemas/templates.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="template" type="TemplateType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="TemplateType">
        <xs:sequence>
            <xs:element name="tabGroup" type="TabGroupType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="group" type="GroupType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="parameter" type="ParameterType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="topLevel" type="xs:boolean" default="false"/>
        <xs:attribute name="fileName" type="xs:string"/>
        <xs:attribute name="unique" type="xs:boolean"/>
        <xs:attribute name="nameFormat" type="xs:string"/>
        <xs:attribute name="primaryParameter" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="TabGroupType">
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="x" type="xs:integer" default="0"/>
        <xs:attribute name="y" type="xs:integer" default="0"/>
        <xs:attribute name="width" type="xs:integer" default="1"/>
        <xs:attribute name="height" type="xs:integer" default="1"/>
    </xs:complexType>

    <xs:complexType name="GroupType">
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="tabGroup" type="xs:string"/>
        <xs:attribute name="x" type="xs:integer" default="0"/>
        <xs:attribute name="y" type="xs:integer" default="0"/>
        <xs:attribute name="width" type="xs:integer" default="1"/>
        <xs:attribute name="height" type="xs:integer" default="1"/>
    </xs:complexType>

    <xs:complexType name="ParameterType">
        <xs:sequence>
            <xs:element name="component" type="ComponentOptionType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="dataType" type="ParameterDataType" use="required"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="type" type="xs:string"/>
        <xs:attribute name="topLevelOnly" type="xs:boolean" default="false"/>
        <xs:attribute name="optional" type="xs:boolean" default="false"/>
        <xs:attribute name="format" type="ParameterFormat"/>
        <xs:attribute name="componentFormat" type="ComponentFormat"/>
        <xs:attribute name="useComponentTypeName" type="xs:boolean" default="false"/>
        <xs:attribute name="group" type="xs:string"/>
        <xs:attribute name="x" type="xs:integer" default="0"/>
        <xs:attribute name="y" type="xs:integer" default="0"/>
        <xs:attribute name="width" type="xs:integer" default="1"/>
        <xs:attribute name="height" type="xs:integer" default="1"/>
        <xs:attribute name="default" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="ComponentOptionType">
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="object" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:simpleType name="ParameterDataType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="float"/>
            <xs:enumeration value="string"/>
            <xs:enumeration value="stringLong"/>
            <xs:enumeration value="object"/>
            <xs:enumeration value="objectSet"/>
            <xs:enumeration value="objectSetUnique"/>
            <xs:enumeration value="reference"/>
            <xs:enumeration value="referenceSet"/>
            <xs:enumeration value="enum"/>
            <xs:enumeration value="expression"/>
            <xs:enumeration value="script"/>
            <xs:enumeration value="scriptFile"/>
            <xs:enumeration value="component"/>
            <xs:enumeration value="tree"/>
            <xs:enumeration value="treeBranch"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ParameterFormat">
        <xs:restriction base="xs:string">
            <xs:enumeration value="attribute"/>
            <xs:enumeration value="child_tag"/>
            <xs:enumeration value="current_tag"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ComponentFormat">
        <xs:restriction base="xs:string">
            <xs:enumeration value="typeAttribute"/>
            <xs:enumeration value="textOrTags"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== finley243/adventure-editor/templates/templates.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/templates.xsd">
    <template id="config" name="Project Configuration" topLevel="false">
        <group id="startTime" name="Start Time" y="5" width="2"/>
        <group id="startDate" name="Start Date" y="4" width="2"/>
        <group id="player" name="Player Settings" x="1" y="0" height="3"/>
        <parameter id="gameName" dataType="string" name="Game Name" format="child_tag" y="0"/>
        <parameter id="interfaceType" dataType="enum" type="interfaceType" name="Interface Type" format="child_tag" y="1"/>
        <parameter id="enableDebugLog" dataType="boolean" name="Enable Debug Log" format="child_tag" y="2"/>
        <parameter id="playerStats" dataType="reference" type="actor" name="Actor Template" format="child_tag" group="player" y="0"/>
        <parameter id="playerID" dataType="string" name="Instance ID" format="child_tag" group="player" y="1" default="player"/>
        <parameter id="playerStartArea" dataType="reference" type="area" name="Start Area" format="child_tag" group="player" y="2"/>
        <parameter id="defaultDamageType" dataType="reference" type="damageType" name="Default Damage Type" format="child_tag" x="0" y="3"/>
        <parameter id="defaultLinkType" dataType="reference" type="linkType" name="Default Link Type" format="child_tag" x="1" y="3"/>
        <parameter id="startTimeHours" dataType="integer" name="Hours" format="child_tag" group="startTime" x="0"/>
        <parameter id="startTimeMinutes" dataType="integer" name="Minutes" format="child_tag" group="startTime" x="1"/>
        <parameter id="startDateYear" dataType="integer" name="Year" format="child_tag" group="startDate" x="0" y="0"/>
        <parameter id="startDateMonth" dataType="integer" name="Month" format="child_tag" group="startDate" x="1" y="0"/>
        <parameter id="startDateDay" dataType="integer" name="Day" format="child_tag" group="startDate" x="0" y="1"/>
        <parameter id="startDateWeekday" dataType="enum" type="weekday" name="Weekday" format="child_tag" group="startDate" x="1" y="1"/>
    </template>
    <template id="room" name="Room" topLevel="true" nameFormat="$id" primaryParameter="id">
        <parameter id="id" dataType="string" name="ID" format="attribute" x="0" y="0"/>
        <parameter id="name" dataType="object" name="Name" type="roomName" x="0" y="1"/>
        <parameter id="faction" dataType="reference" name="Faction" type="faction" format="attribute" optional="true" x="0" y="2"/>
        <parameter id="restriction" dataType="enum" type="areaRestrictionType" name="Restriction Type" format="attribute" optional="true" default="PUBLIC" x="0" y="3"/>
        <parameter id="allowAllies" dataType="boolean" name="Allow Allies" format="attribute" optional="true" default="false" x="0" y="4"/>
        <parameter id="description" dataType="object" name="Description" type="description" optional="true" x="1" y="0" height="5"/>
        <parameter id="script" dataType="objectSetUnique" type="scriptWithTriggerRoom" name="Script Triggers" x="2" y="0" height="3"/>
    </template>
    <template id="area" name="Area" topLevel="true" nameFormat="$id" primaryParameter="id">
        <parameter id="id" dataType="string" name="ID" format="attribute" x="0" y="0"/>
        <parameter id="name" dataType="object" name="Name" type="areaName" optional="true" x="0" y="1"/>
        <parameter id="room" dataType="reference" type="room" name="Room" format="attribute" optional="true" x="0" y="2"/>
        <parameter id="landmark" dataType="reference" name="Landmark" type="objectInstance" format="attribute" optional="true" x="0" y="3"/>
        <parameter id="faction" dataType="reference" name="Faction" type="faction" format="attribute" optional="true" x="0" y="4"/>
        <parameter id="restriction" dataType="enum" type="areaRestrictionType" name="Restriction Type" format="attribute" optional="true" default="PUBLIC" x="0" y="5"/>
        <parameter id="allowAllies" dataType="boolean" name="Allow Allies" format="attribute" optional="true" default="false" x="0" y="6"/>
        <parameter id="description" dataType="object" name="Description" type="description" optional="true" x="1" y="0" height="3"/>
        <parameter id="link" dataType="objectSetUnique" name="Links" type="areaLink" x="1" y="3" height="2"/>
        <parameter id="script" dataType="objectSetUnique" type="scriptWithTriggerArea" name="Script Triggers" x="1" y="5" height="2"/>
        <parameter id="object" dataType="referenceSet" type="objectInstance" name="Objects" x="2" y="0" height="2"/>
        <parameter id="item" dataType="objectSetUnique" type="itemInstance" name="Items" x="2" y="2" height="2"/>
        <parameter id="actor" dataType="referenceSet" type="actorInstance" name="Actors" x="2" y="4" height="2"/>
    </template>
    <template id="objectInstance" name="Object" topLevel="false" unique="true" nameFormat="$id" primaryParameter="id">
        <parameter id="template" dataType="reference" type="object" name="Template" format="attribute" y="0"/>
        <parameter id="id" dataType="string" name="ID" format="attribute" y="1"/>
        <parameter id="startDisabled" dataType="boolean" name="Start Disabled" format="attribute" default="false" y="2"/>
        <parameter id="startHidden" dataType="boolean" name="Start Hidden" format="attribute" default="false" y="3"/>
        <parameter id="localVar" dataType="objectSetUnique" type="localVar" y="4"/>
    </template>
    <template id="itemInstance" name="Item" topLevel="false" nameFormat="$template" primaryParameter="template">
        <parameter id="template" dataType="reference" type="item" name="Template" format="attribute" y="0"/>
        <parameter id="id" dataType="string" name="ID" format="attribute" optional="true" y="1"/>
    </template>
    <template id="actorInstance" name="Actor" topLevel="false" unique="true" nameFormat="$id" primaryParameter="id">
        <parameter id="template" dataType="reference" type="actor" name="Template" format="attribute" y="0"/>
        <parameter id="id" dataType="string" name="ID" format="attribute" y="1"/>
        <parameter id="startDead" dataType="boolean" name="Start Dead" default="false" format="attribute" y="2"/>
        <parameter id="startDisabled" dataType="boolean" name="Start Disabled" default="false" format="attribute" y="3"/>
        <parameter id="descriptor" dataType="string" name="Descriptor" optional="true" format="child_tag" y="4"/>
        <parameter id="behaviors" dataType="object" type="actorBehaviorSet" name="Behaviors" y="5"/>
    </template>
    <template id="actorBehaviorSet" name="Behaviors" topLevel="false">
        <!--<parameter id="behavior" dataType="objectSet" type="actorBehavior" name="Behaviors"/>-->
        <parameter id="behavior" dataType="tree" type="actorBehavior" name="Behaviors"/>
    </template>
    <template id="actorBehavior" name="Behavior" topLevel="false" nameFormat="$behaviorType">
        <tabGroup id="scriptTabs" name="Scripts" x="0" y="1"/>
        <group id="scriptStartGroup" name="Start" tabGroup="scriptTabs"/>
        <group id="scriptEachRoundGroup" name="Each Round" tabGroup="scriptTabs"/>
        <parameter id="condition" dataType="string" name="Condition" optional="true" x="0" y="0"/>
        <parameter id="scriptStart" dataType="script" name="Start Script" optional="true" group="scriptStartGroup"/>
        <parameter id="scriptEachRound" dataType="script" name="Each Round Script" optional="true" group="scriptEachRoundGroup"/>
        <parameter id="behaviorType" dataType="component" componentFormat="typeAttribute" useComponentTypeName="true" name="Behavior Type" x="1" y="0" height="2">
            <component id="move" name="Move" object="behaviorMove"/>
            <component id="action" name="Action" object="behaviorAction"/>
            <component id="use" name="Use" object="behaviorUse"/>
            <component id="guard" name="Guard" object="behaviorGuard"/>
            <component id="follow" name="Follow" object="behaviorFollow"/>
            <component id="procedure" name="Procedure" object="behaviorProcedure"/>
        </parameter>
    </template>
    <template id="idle" name="Idle" topLevel="false" nameFormat="$phrase">
        <parameter id="condition" dataType="string" name="Condition" format="child_tag" optional="true" y="0"/>
        <parameter id="phrase" dataType="string" name="Phrase" format="child_tag" y="1"/>
    </template>
    <template id="behaviorCommonObject" name="Core" topLevel="false">
        <parameter id="duration" dataType="integer" name="Duration" default="0" format="attribute" y="0"/>
        <parameter id="idle" dataType="objectSet" type="idle" name="Idles" y="1"/>
    </template>
    <template id="behaviorMove" name="Move" topLevel="false" nameFormat="Move ($area)">
        <parameter id="core" dataType="object" type="behaviorCommonObject" format="current_tag" y="0"/>
        <parameter id="area" dataType="reference" type="area" name="Target Area" format="attribute" y="1"/>
    </template>
    <template id="behaviorAction" name="Action" topLevel="false" nameFormat="Action ($action)">
        <parameter id="core" dataType="object" type="behaviorCommonObject" format="current_tag" y="0"/>
        <parameter id="action" dataType="reference" type="action" name="Action" format="attribute" y="1"/>
        <parameter id="actionCondition" dataType="string" name="Action Condition" format="child_tag" y="2"/>
    </template>
    <template id="behaviorUse" name="Use" topLevel="false" nameFormat="Use ($object)">
        <parameter id="core" dataType="object" type="behaviorCommonObject" format="current_tag" y="0"/>
        <parameter id="object" dataType="reference" type="objectInstance" name="Target Object" format="attribute" y="1"/>
        <parameter id="slot" dataType="string" name="Use Slot" format="attribute" y="2"/>
    </template>
